/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.BaseDatos;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author anfel
 */
public class MenuProfesional extends javax.swing.JFrame {

    /**
     * Creates new form MenuProfesional
     */
    private static GestionarProfesional gestionarProfesional;
    private static GestionarPropietario gestionarPropietario;
    private int xMouse, yMouse;
    private final BaseDatos bd;
    private Login login;

    public MenuProfesional() {
        initComponents();
        rsscalelabel.RSScaleLabel.setScaleLabel(lblAvatar, "src/Vista/Imagenes/AvatarVeterinario.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lblPanelFondo, "src/Vista/Imagenes/FondoMenu.png");
        bd = new BaseDatos();
        tblPanel.setVisible(false);
        btnAgregarEntidad.setVisible(false);
        btnActualizar.setVisible(false);
        btnBuscar.setVisible(false);
        txtBuscar.setVisible(false);
        tblEntidades.setRowHeight(35);
        panelFondo.setLayout(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnGestionarProfesionales = new javax.swing.JPanel();
        lblGestionarProfesionales = new javax.swing.JLabel();
        btnGestionarPropietarios = new javax.swing.JPanel();
        lblGestionarPropietarios = new javax.swing.JLabel();
        btnGestionarPacientes = new javax.swing.JPanel();
        lblGestionarPacientes = new javax.swing.JLabel();
        btnConfiguraciones = new javax.swing.JPanel();
        lblCerrarSesion = new javax.swing.JLabel();
        lblAvatar = new javax.swing.JLabel();
        exitPanel = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        panelFondo = new javax.swing.JPanel();
        lblBienvenido = new java.awt.Label();
        tblPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEntidades = new javax.swing.JTable();
        btnAgregarEntidad = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        lblPanelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(110, 77, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGestionarProfesionales.setBackground(new java.awt.Color(110, 77, 0));
        btnGestionarProfesionales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblGestionarProfesionales.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 12)); // NOI18N
        lblGestionarProfesionales.setForeground(new java.awt.Color(255, 255, 255));
        lblGestionarProfesionales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGestionarProfesionales.setText("GESTIONAR PROFESIONALES");
        lblGestionarProfesionales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGestionarProfesionalesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGestionarProfesionalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGestionarProfesionalesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnGestionarProfesionalesLayout = new javax.swing.GroupLayout(btnGestionarProfesionales);
        btnGestionarProfesionales.setLayout(btnGestionarProfesionalesLayout);
        btnGestionarProfesionalesLayout.setHorizontalGroup(
            btnGestionarProfesionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGestionarProfesionales, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        btnGestionarProfesionalesLayout.setVerticalGroup(
            btnGestionarProfesionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGestionarProfesionales, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel2.add(btnGestionarProfesionales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        btnGestionarPropietarios.setBackground(new java.awt.Color(110, 77, 0));
        btnGestionarPropietarios.setForeground(new java.awt.Color(255, 255, 255));

        lblGestionarPropietarios.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 12)); // NOI18N
        lblGestionarPropietarios.setForeground(new java.awt.Color(255, 255, 255));
        lblGestionarPropietarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGestionarPropietarios.setText("GESTIONAR PROPIETARIOS");
        lblGestionarPropietarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGestionarPropietarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGestionarPropietariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGestionarPropietariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGestionarPropietariosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnGestionarPropietariosLayout = new javax.swing.GroupLayout(btnGestionarPropietarios);
        btnGestionarPropietarios.setLayout(btnGestionarPropietariosLayout);
        btnGestionarPropietariosLayout.setHorizontalGroup(
            btnGestionarPropietariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGestionarPropietarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnGestionarPropietariosLayout.setVerticalGroup(
            btnGestionarPropietariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnGestionarPropietariosLayout.createSequentialGroup()
                .addComponent(lblGestionarPropietarios, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(btnGestionarPropietarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 190, 100));

        btnGestionarPacientes.setBackground(new java.awt.Color(110, 77, 0));

        lblGestionarPacientes.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 12)); // NOI18N
        lblGestionarPacientes.setForeground(new java.awt.Color(255, 255, 255));
        lblGestionarPacientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGestionarPacientes.setText("GESTIONAR PACIENTES");
        lblGestionarPacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGestionarPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGestionarPacientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGestionarPacientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGestionarPacientesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnGestionarPacientesLayout = new javax.swing.GroupLayout(btnGestionarPacientes);
        btnGestionarPacientes.setLayout(btnGestionarPacientesLayout);
        btnGestionarPacientesLayout.setHorizontalGroup(
            btnGestionarPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGestionarPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        btnGestionarPacientesLayout.setVerticalGroup(
            btnGestionarPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGestionarPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel2.add(btnGestionarPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 190, -1));

        btnConfiguraciones.setBackground(new java.awt.Color(110, 77, 0));
        btnConfiguraciones.setForeground(new java.awt.Color(255, 255, 255));
        btnConfiguraciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblCerrarSesion.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 12)); // NOI18N
        lblCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrarSesion.setText("CERRAR SESIÓN");
        lblCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnConfiguracionesLayout = new javax.swing.GroupLayout(btnConfiguraciones);
        btnConfiguraciones.setLayout(btnConfiguracionesLayout);
        btnConfiguracionesLayout.setHorizontalGroup(
            btnConfiguracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        btnConfiguracionesLayout.setVerticalGroup(
            btnConfiguracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCerrarSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel2.add(btnConfiguraciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 190, 100));

        lblAvatar.setBackground(new java.awt.Color(255, 255, 255));
        lblAvatar.setForeground(new java.awt.Color(255, 255, 255));
        lblAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvatar.setText("FOTO");
        jPanel2.add(lblAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 21, 135, 135));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 190, 680));

        exitPanel.setBackground(new java.awt.Color(255, 255, 255));
        exitPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                exitPanelMouseDragged(evt);
            }
        });
        exitPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitPanelMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        lblExit.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lblExit.setForeground(new java.awt.Color(0, 0, 0));
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("X");
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout exitPanelLayout = new javax.swing.GroupLayout(exitPanel);
        exitPanel.setLayout(exitPanelLayout);
        exitPanelLayout.setHorizontalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitPanelLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1240, Short.MAX_VALUE))
        );
        exitPanelLayout.setVerticalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitPanelLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(exitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 40));

        panelFondo.setBackground(new java.awt.Color(255, 251, 245));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBienvenido.setAlignment(java.awt.Label.CENTER);
        lblBienvenido.setBackground(new java.awt.Color(255, 251, 245));
        lblBienvenido.setFont(new java.awt.Font("Roboto Black", 1, 28)); // NOI18N
        lblBienvenido.setText("BIENVENIDO PROFESIONAL");
        panelFondo.add(lblBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 25, -1, 45));

        tblPanel.setBackground(new java.awt.Color(204, 204, 204));
        tblPanel.setMinimumSize(new java.awt.Dimension(0, 350));
        tblPanel.setPreferredSize(new java.awt.Dimension(960, 460));

        tblEntidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEntidades);

        javax.swing.GroupLayout tblPanelLayout = new javax.swing.GroupLayout(tblPanel);
        tblPanel.setLayout(tblPanelLayout);
        tblPanelLayout.setHorizontalGroup(
            tblPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
        );
        tblPanelLayout.setVerticalGroup(
            tblPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        panelFondo.add(tblPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 142, 990, 470));

        btnAgregarEntidad.setBackground(new java.awt.Color(255, 189, 89));
        btnAgregarEntidad.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 14)); // NOI18N
        btnAgregarEntidad.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarEntidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarEntidadMouseClicked(evt);
            }
        });
        panelFondo.add(btnAgregarEntidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 620, 170, 39));

        btnActualizar.setBackground(new java.awt.Color(255, 189, 89));
        btnActualizar.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });
        panelFondo.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 620, 170, 39));

        txtBuscar.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        txtBuscar.setMinimumSize(new java.awt.Dimension(68, 30));
        txtBuscar.setPreferredSize(new java.awt.Dimension(75, 30));
        panelFondo.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 860, 40));

        btnBuscar.setBackground(new java.awt.Color(110, 77, 0));

        lblBuscar.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuscar.setText("Buscar");
        lblBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBuscarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnBuscarLayout = new javax.swing.GroupLayout(btnBuscar);
        btnBuscar.setLayout(btnBuscarLayout);
        btnBuscarLayout.setHorizontalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        btnBuscarLayout.setVerticalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panelFondo.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 100, 110, 40));

        lblPanelFondo.setText("jLabel1");
        panelFondo.add(lblPanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 680));

        jPanel1.add(panelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 1090, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblGestionarProfesionalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionarProfesionalesMouseClicked
        bd.mostrarProfesionales(tblEntidades);

        btnBuscar.setVisible(true);
        txtBuscar.setVisible(true);
        btnAgregarEntidad.setText("Agregar Profesional");

        tblPanel.setVisible(true);
        btnAgregarEntidad.setVisible(true);

        btnActualizar.setBounds(202, 620, 170, 39);
        btnActualizar.setVisible(true);

        panelFondo.revalidate();
        panelFondo.repaint();

    }//GEN-LAST:event_lblGestionarProfesionalesMouseClicked

    private void lblGestionarProfesionalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionarProfesionalesMouseEntered
        btnGestionarProfesionales.setBackground(Color.WHITE);
        lblGestionarProfesionales.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblGestionarProfesionalesMouseEntered

    private void lblGestionarProfesionalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionarProfesionalesMouseExited
        btnGestionarProfesionales.setBackground(new Color(110, 77, 0));
        lblGestionarProfesionales.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblGestionarProfesionalesMouseExited

    private void lblCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseEntered
        btnConfiguraciones.setBackground(Color.WHITE);
        lblCerrarSesion.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblCerrarSesionMouseEntered

    private void lblCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseExited
        btnConfiguraciones.setBackground(new Color(110, 77, 0));
        lblCerrarSesion.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblCerrarSesionMouseExited

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        bd.cerrarConexion();
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        exitBtn.setBackground(Color.red);
        lblExit.setForeground(Color.white);
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        exitBtn.setBackground(Color.white);
        lblExit.setForeground(Color.black);
    }//GEN-LAST:event_lblExitMouseExited

    private void exitPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_exitPanelMouseDragged

    private void exitPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPanelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_exitPanelMousePressed

    private void lblGestionarPropietariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionarPropietariosMouseClicked
        bd.mostrarPropietarios(tblEntidades);

        btnBuscar.setVisible(true);
        txtBuscar.setVisible(true);
        btnAgregarEntidad.setText("Agregar Propietario");

        tblPanel.setVisible(true);
        btnAgregarEntidad.setVisible(true);

        btnActualizar.setBounds(202, 620, 170, 39);
        btnActualizar.setVisible(true);

        panelFondo.revalidate();
        panelFondo.repaint();

    }//GEN-LAST:event_lblGestionarPropietariosMouseClicked

    private void lblGestionarPropietariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionarPropietariosMouseEntered
        btnGestionarPropietarios.setBackground(Color.WHITE);
        lblGestionarPropietarios.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblGestionarPropietariosMouseEntered

    private void lblGestionarPropietariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionarPropietariosMouseExited
        btnGestionarPropietarios.setBackground(new Color(110, 77, 0));
        lblGestionarPropietarios.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblGestionarPropietariosMouseExited

    private void lblCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseClicked
        bd.cerrarConexion();
        this.setVisible(false);
        login = new Login();
        login.setVisible(true);

    }//GEN-LAST:event_lblCerrarSesionMouseClicked

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
        switch (btnAgregarEntidad.getText()) {
            case "Agregar Profesional":
                bd.mostrarProfesionales(tblEntidades);
                break;
            case "Agregar Propietario":
                bd.mostrarPropietarios(tblEntidades);
                break;
            default:
                bd.mostrarPacientes(tblEntidades);
                break;
        }
    }//GEN-LAST:event_btnActualizarMouseClicked

    private void lblBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMouseEntered
        btnBuscar.setBackground(new Color(128, 77, 0));
        lblBuscar.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblBuscarMouseEntered

    private void lblBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMouseExited
        btnBuscar.setBackground(new Color(110, 77, 0));
        lblBuscar.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblBuscarMouseExited

    private void lblBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMouseClicked
        String textoBusqueda = txtBuscar.getText();
        String nameTable;

        if (btnAgregarEntidad.getText().equals("Agregar Propietario")) {
            nameTable = "propietarios";
        } else if (btnAgregarEntidad.getText().equals("Agregar Profesional")) {
            nameTable = "profesionales";
        } else {
            nameTable = "pacientes";
        }

        bd.buscarEntidad(tblEntidades, textoBusqueda, nameTable);

    }//GEN-LAST:event_lblBuscarMouseClicked

    private void lblGestionarPacientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionarPacientesMouseEntered
        btnGestionarPacientes.setBackground(Color.WHITE);
        lblGestionarPacientes.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblGestionarPacientesMouseEntered

    private void lblGestionarPacientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionarPacientesMouseExited
        btnGestionarPacientes.setBackground(new Color(110, 77, 0));
        lblGestionarPacientes.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblGestionarPacientesMouseExited

    private void lblGestionarPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionarPacientesMouseClicked
        btnActualizar.setBounds(26, 620, 170, 39);
        btnActualizar.setVisible(true);

        bd.mostrarPacientes(tblEntidades);
        btnBuscar.setVisible(true);
        txtBuscar.setVisible(true);
        tblPanel.setVisible(true);
        btnAgregarEntidad.setText("Agregar Pacientes");
        btnAgregarEntidad.setVisible(false);

        panelFondo.revalidate();
        panelFondo.repaint();

    }//GEN-LAST:event_lblGestionarPacientesMouseClicked

    private void btnAgregarEntidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarEntidadMouseClicked

        //Configurar el botón para que identifique cuándo se muestran los propietarios y los profesionales.
        if (btnAgregarEntidad.getText().equals("Agregar Profesional")) {
            gestionarProfesional = new GestionarProfesional();
            gestionarProfesional.setVisible(true);
        } else {
            gestionarPropietario = new GestionarPropietario();
            gestionarPropietario.setVisible(true);
        }

    }//GEN-LAST:event_btnAgregarEntidadMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregarEntidad;
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JPanel btnConfiguraciones;
    private javax.swing.JPanel btnGestionarPacientes;
    private javax.swing.JPanel btnGestionarProfesionales;
    private javax.swing.JPanel btnGestionarPropietarios;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JPanel exitPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvatar;
    private java.awt.Label lblBienvenido;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCerrarSesion;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblGestionarPacientes;
    private javax.swing.JLabel lblGestionarProfesionales;
    private javax.swing.JLabel lblGestionarPropietarios;
    private javax.swing.JLabel lblPanelFondo;
    private javax.swing.JPanel panelFondo;
    public javax.swing.JTable tblEntidades;
    private javax.swing.JPanel tblPanel;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
